In [7]:
import pandas as pd

# Define the file path
file_path = 'data/scraped_data/muse/csv/muse_scrapped_data.csv'

# Read the CSV file into a pandas DataFrame
df_muse = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
df_muse.head()

,Job Title,Company Name,Location,Publication Date,Categories,Experience Level,Job Link,Full/Part Time
0,Senior IT Enterprise Architect (w/m/d),Siemens,"Berlin, Germany",2023-05-16T23:40:22Z,Computer and IT,Senior Level,https://www.themuse.com/jobs/siemens/senior-it...,NaN
1,Fahrleitungsmonteur (w/m/d) Fahrleitungs- und ...,Siemens,"Berlin, Germany",2023-01-24T00:42:10Z,Computer and IT,Mid Level,https://www.themuse.com/jobs/siemens/fahrleitu...,NaN
2,(Junior) Business Analyst (f/m/d),Siemens,"Flexible / Remote, Warsaw, Poland",2023-05-18T23:39:44Z,Data and Analytics,Mid Level,https://www.themuse.com/jobs/siemens/junior-bu...,Full-time
3,Lead Data Science Engineer - Remote US,Siemens,"Chicago, IL, Flexible / Remote",2023-05-16T23:40:21Z,Data and Analytics,Senior Level,https://www.themuse.com/jobs/siemens/lead-data...,Full-time
4,IT Operations Analyst (w/m/d) Firewall,Siemens,"Munich, Germany",2023-01-28T23:37:48Z,Computer and IT,Mid Level,https://www.themuse.com/jobs/siemens/it-operat...,Full-time

In [6]:
# Define the file path
file_path = 'data/scraped_data/adjurna/csv/adzuna_scrapped_data.csv'

# Read the CSV file into a pandas DataFrame
df_adjurna = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
df_adjurna.head()

,company,title,location,link,job_posted,category,source,description
0,Süddeutsche Zeitung Digitale Medien GmbH,Werkstudent (m/w/d) Data Science,"München, München (Kreis)",https://www.adzuna.de/land/ad/4559596995?se=AC...,2024-02-06 13:44:59+00:00,Aufgaben Profil Wir bieten Die Süddeutsche Zei...,Sonstige/Allgemeine Stellen,Adzuna
1,Technische Universität München,Professor in Empirical Economics and Data Science,"Altstadt-Lehel, München",https://www.adzuna.de/land/ad/4570297796?se=AC...,2024-02-15 17:42:47+00:00,The Technical University of Munich (TUM) invit...,Unknown,Adzuna
2,O2 Telefónica,Duales Studium Data Science und Scientific Com...,"München, München (Kreis)",https://www.adzuna.de/land/ad/4570047587?se=AC...,2024-02-15 13:34:32+00:00,"Vertragsart: Vollzeit, befristet Standort: Tel...",Unknown,Adzuna
3,Hoffmann Group,Data Science Product Manager (m/f/d),"München, München (Kreis)",https://www.adzuna.de/land/ad/4546865990?se=AC...,2024-01-27 13:21:18+00:00,"More than 4,000 highly motivated employees in ...",Stellen aus Wissenschaft & Qualitätssicherung,Adzuna
4,ProSiebenSat.1 Careers,Intern Data Science & AI (m/f/d),"München, München (Kreis)",https://www.adzuna.de/land/ad/4548461379?se=AC...,2024-01-29 13:19:48+00:00,Let's CreateMomentsThatMatter together ProSieb...,Stellen aus Wissenschaft & Qualitätssicherung,Adzuna